### ISSUE TITLE
Remove text from DIV

### ISSUE THREAD

**Issue by AsherSpurr** [AsherSpurr/fitlit#31]
### HTML
DIV on line 76 should not have any attributes
-remove text
-consider adding a h3 element or looking up ways to identify a form

**Comment by crotteau** [comment]
Are you saying I shouldn't have the class listed as an attribute? My HTML may be slightly off from yours because line 76 refers to `<div class="hydration-left-cont">`. 

I'm assuming you're referring to my line 77 `<div class="hydration-user-input"> Add Today's Hydration Data!` Which I'll remove the innerText and label it another way, but I'm unsure why the class attribute can't be there/what you mean by that

**Comment by AsherSpurr** [comment]
Yes, that's what I was referring to, attribute was the wrong word.
